In [1]:
import numpy as np

In [9]:
a  = np.ones(3)
print(a)


[1. 1. 1.]


In [11]:
b = np.empty(4)
print(b)

[4.70560276e-310 0.00000000e+000 4.70450818e-310 4.70450820e-310]


In [18]:
c = np.arange(1,90,4)
print(c)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89]


In [24]:
d = np.linspace(1,10,3)
print(d)

[ 1.   5.5 10. ]


In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])



print(np.concatenate((b, a)))


[5 6 7 8 1 2 3 4]


In [38]:
x = np.array([[1, 2,3], [3, 4,3]])
y = np.array([[5, 6,3],[3, 4,3]])



d = np.concatenate((x, y), axis=1)


print(d)

[[1 2 3 5 6 3]
 [3 4 3 3 4 3]]


In [39]:
print(d.ndim)

2


In [41]:
d = np.concatenate((x, y), axis=0)

print(d)
print(d.ndim)

[[1 2 3]
 [3 4 3]
 [5 6 3]
 [3 4 3]]
2


In [42]:
a = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])


In [43]:
print(a)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [44]:
print(a.shape)

(2, 3, 4)


In [45]:
print(a.ndim)

3


In [46]:
print(a.size)

24


In [48]:
print(d.size)

12


In [49]:
print(d.shape)

(4, 3)


In [54]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [59]:
b = a.reshape(2,5)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [60]:
a =  np.arange(10)
print(a.shape)

(10,)


In [61]:
a.ndim

1

In [62]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a.shape

(10,)

In [69]:
a = a[np.newaxis, :]

In [70]:
a.shape

(1, 10)

In [75]:
print(a.shape)


(1, 10)


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [72]:
a.ndim

2

In [73]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [112]:
arr = np.arange(9)

In [113]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [114]:
y = np.stack(arr, axis=0) 

In [115]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8])